version: '3.9'

services:
   ordermanager:
      container_name: ordermanager
      depends_on:
         - mysql
      image: alexintelc/ordermanager:latest
#      build:                              #use this instead of image if you want to run MySQL + SpringBoot app locally on docker
#         context: .
#         dockerfile: Dockerfile 
      ports:
         - "8080:8080" 
      restart: on-failure
      env_file:
         - .env

   mysql:
      container_name: mysql
      image: mysql:latest
      restart: unless-stopped
      volumes:
         - rv-volume:/var/lib/mysql
      env_file:
         - .env
      ports:
         - "3036:3036" 

volumes:
   rv-volume:
