services:
   ordermanager:
      container_name: ordermanager
      depends_on:
         - mysql
      image: alexintelc/ordermanager:latest   #In case this is executed from Mac M1, comment line 6 and uncomment lines 7-10
#      build:
#         context: .
#         dockerfile: Dockerfile
#      platform: linux/amd64      #Specifies platform
      ports:
         - "8080:8080" 
      restart: on-failure
      env_file:
         - .env
   mysql:
      container_name: mysql
      image: mysql:latest
      restart: unless-stopped
      volumes:
         - rv-volume:/var/lib/mysql
      env_file:
         - .env
      ports:
         - "3036:3036" 
volumes:
   rv-volume: