spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-circular-references: true 
  h2:
    console:
      enabled: true
      path: /console/                # http://localhost:8080/console
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false     # Jackson deserializer is used also for converting exception, this is needed when de/serializer is not found
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:standalone}"

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor: INFO

thirdparties:
  google:
    key: "${GOOGLE_API_KEY:AIzaSyDFW_s8pzd3mG1OKTsZkLeKec0aYh5zVEw}"
  jwt:
    key: "${JWT_KEY:javax.crypto.spec.SecretKeySpec@5881a62}"
