spring:
  profiles:
    active: standalone
#   when running docker, it overrides the profile using the spring profile "docker" defined in .env 
    
#logging:
#  level:
#    org.springframework: DEBUG

thirdparties:
  google:
    key: AIzaSyAtmF-sdGsz0tdqnxqSilJ6kVagwsMie90