spring:
  h2:
    console:
      enabled: true
      path: /console/ # http://localhost:8080/console
  profiles:
    active: standalone # when running docker, it overrides the profile using the spring profile "docker" defined in .env
  main:
    allow-circular-references: true 
    
logging:
  level:
    root: INFO
    org.springframework: TRACE
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor: INFO

thirdparties:
  google:
    key: YOUR_API_KEY