spring:
  h2:
    console:
      enabled: true
      path: /console/ # http://localhost:8080/console
#  profiles:
#    active: docker 
#    active: standalone
  main:
    allow-circular-references: true 
    
logging:
  level:
    root: INFO
    org.springframework: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor: INFO

thirdparties:
  google:
    key: "${GOOGLE_API_KEY:YOUR_API_KEY}"
  jwt:
    key: "${JWT_KEY:javax.crypto.spec.SecretKeySpec@5881a62}"