CREATE TABLE IF NOT EXISTS orders (
    ID BIGINT generated by default as identity,
    DISTANCE INT NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    VERSION BIGINT,
    primary key (ID)
);

CREATE TABLE IF NOT EXISTS users (
    ID BIGINT generated by default as identity,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    primary key (ID)
);